import test from "@playwright/test";


// ───────────────────────────────────────────────
// Radio Button Locators in Playwright
// ───────────────────────────────────────────────
//
// Role:
//   - Radio buttons have the role: "radio".
//   - You can confirm this in the browser’s DevTools → Accessibility tab.
//
// Usage:
//   - Use getByRole('radio') with the visible name of the option.
//   - Add exact: true if multiple similar names exist.
//
// Example:
//   await page.getByRole('radio', { name: 'Java', exact: true }).click();
//
// Notes:
//   - Role-based locators are stable and preferred over CSS/XPath.
//   - Accessibility roles (like "radio") are generated by the browser,
//     not by Playwright itself.
//   - Always validate the role in Accessibility view if unsure.
//
// ───────────────────────────────────────────────

test("RadioButton test", async ({ page }) => {
    await page.goto("https://www.shapemyinterview.com/study/playwright-locator-playground.html?v=2026-07-26");
    await page.getByRole('radio', { name: 'Java', exact: true }).click();
    //  await page.pause();

})




// ───────────────────────────────────────────────
//Checkbox Locators in Playwright
// ───────────────────────────────────────────────
//
// Role:
//   - Checkboxes have the role: "checkbox".
//   - Confirm via browser DevTools → Accessibility tab.
//
// Usage:
//   - Use getByRole('checkbox') with the visible name of the option.
//   - Example:
//       await page.getByRole('checkbox', { name: 'Cypress' }).click();
//
// Actions:
//   - .check()   → Ensures the checkbox is selected.
//   - .uncheck() → Ensures the checkbox is cleared.
//   - .click()   → Toggles the checkbox state (select/unselect).
//
// Example:
//   await page.getByRole('checkbox', { name: 'Cypress' }).check();
//   await page.getByRole('checkbox', { name: 'Playwright' }).uncheck();
//
// Debugging:
//   - Use highlight() to visually confirm the locator.
//   - Use page.pause() to inspect interactively in Playwright Inspector.
//
// Notes:
//   - Role-based locators are stable and preferred over CSS/XPath.
//   - Accessibility roles (like "checkbox") are generated by the browser,
//     not by Playwright itself.
//   - Always validate the role in Accessibility view if unsure.
//   - Prefer .check() / .uncheck() over .click() for clarity in tests.
//
// ───────────────────────────────────────────────

test("Checkbox test", async ({ page }) => {
    await page.goto("https://www.shapemyinterview.com/study/playwright-locator-playground.html?v=2026-07-26");
    await page.getByRole('checkbox', { name: 'Cypress' }).check();
    //  await page.pause();

})