// ───────────────────────────────────────────────
// Locators in Playwright
// ───────────────────────────────────────────────
//
// Ref Link: https://playwright.dev/docs/locators
//
// Definition:
//   - Elements are found in the webpage.
//   - To interact with these elements, Playwright uses "locators".
//   - A locator is a handle to find and perform actions on elements.
//
// Key Features:
//   - Auto-waiting → Playwright waits for elements to be ready (visible, enabled).
//   - Retry-ability → Locators re-query elements if the DOM changes.
//   - Chaining → Locators can be chained for precision.
//   - Collections → Use .all() to work with multiple elements.
//
// Example:
//   await page.getByRole('button', { name: 'Login' }).click();
//   await page.getByLabel('Username').fill('Jagadish');
//
// Best Practices:
//   - Prefer accessibility locators (roles, labels, text) → more stable.
//   - Avoid brittle CSS/XPath selectors unless necessary.
//   - Keep locators descriptive for maintainability.
//   - Use Playwright Codegen (npx playwright codegen) to generate locators quickly.
//
// ───────────────────────────────────────────────
//
// Ways to interact with elements using locators:
//
// 1. User Visibility Way (Accessibility / Semantic / Role-based locators)
//    - Preferred method (stable, user-centric).
//    - Examples:
//        • Text field → Role: textbox + visible name
//        • Forgotten password link → Role: link + visible name
//        • Login button → Role: button + visible name
//        • SearchBox field → Role: searchbox + visible name

//
//    - Use page.getBy* methods for accessibility:
//        • page.getByRole()        → Locate by accessibility role
//        • page.getByLabel()       → Locate form controls by label
//        • page.getByText()        → Locate by visible text content
//        • page.getByPlaceholder() → Locate inputs by placeholder text
//        • page.getByAltText()     → Locate images by alt text
//        • page.getByTitle()       → Locate by title attribute
//        • page.getByTestId()      → Locate by data-testid attribute
//
//    - Note: These locators cannot be directly checked in DOM like Selenium.
//            Use Codegen → npx playwright codegen
//
// 2. Technical Way (DOM-based locators: XPath / CSS)
//    - Less stable, can break if DOM changes.
//    - Example:
//        page.locator("xpath/css")
//
// ───────────────────────────────────────────────
//
// Locator Priority (Recommended order):
//   1. getByRole
//   2. getByLabel
//   3. getByText
//   4. CSS
//   5. XPath
//
// ───────────────────────────────────────────────


// ───────────────────────────────────────────────
//  Locating Headers with getByRole
// ───────────────────────────────────────────────
//
// Usage:
//   - Headers (h1, h2, h3, etc.) can be located using getByRole('heading').
//   - You can specify the visible text (name) of the header.
//   - Optionally, you can also specify the header level.
//
// Examples:
//   await page.getByRole('heading', { name: 'Return Customer' });
//
//   // With level specified (e.g., <h3>Return Customer</h3>):
//   await page.getByRole('heading', { name: 'Return Customer', level: 3 });
//
// Notes:
//   - The "level" option is applicable only for headings (h1–h6).
//   - Useful for distinguishing between multiple headings with the same text.
//   - Prefer role-based locators for stability and accessibility compliance.
//
// ───────────────────────────────────────────────



// ───────────────────────────────────────────────
// Notes: Finding Roles for Locators
// ───────────────────────────────────────────────
//
// Important:
//   - If you are not sure about the role of an element,
//     you can inspect it in the browser’s DevTools.
//
// Steps:
//   1. Right-click on the element → Inspect.
//   2. Go to the "Accessibility" tab in DevTools.
//   3. Check the "Role" property shown there.
//   4. Use that role in Playwright locators (e.g., getByRole).
//
// Example:
//   await page.getByRole('heading', { name: 'Return Customer' });
//   await page.getByRole('button', { name: 'Login' });
//
// Notes:
//   - These roles are generated by the browser’s accessibility tree,
//     not by Playwright itself.
//   - Playwright simply consumes the role information exposed by the browser.
//   - This ensures locators are stable, semantic, and accessibility-compliant.
//
// ───────────────────────────────────────────────


//we can test getbyrole using locatorlabs  as well through browser itself


//getByRole : 

